function trackers=configTrackers(benchmark)
trackers_otb2013 ={ 
    struct('name','MDNet','namePaper','MDNet'),...%OPE
    struct('name','CCOT','namePaper','CCOT'),...
    struct('name','SiamFC','namePaper','SiamFC'),...
    struct('name','SiamFC_3s','namePaper','SiamFC_3s'),...
    struct('name','SINT_noflow_TRE','namePaper','SINT_noflow'),...
    struct('name','SINT_flow','namePaper','SINT_flow'),...%OPE
    struct('name','SCT4','namePaper','SCT4'),...%OPE
    struct('name','SCT6','namePaper','SCT6'),...%OPE
    struct('name','SRDCFdecon','namePaper','SRDCFdecon'),...
    struct('name','HDT','namePaper','HDT'),...
    struct('name','Staple','namePaper','Staple'),...
    struct('name','DLSSVM','namePaper','DLSSVM'),...
    struct('name','Scale_DLSSVM','namePaper','Scale_DLSSVM'),...
    struct('name','SRDCF','namePaper','SRDCF'),...
    struct('name','DeepSRDCF','namePaper','DeepSRDCF'),...
    struct('name','CNN-SVM','namePaper','CNN-SVM'),...%OPE
    struct('name','FCNT','namePaper','FCNT'),...%OPE
    struct('name','CF2','namePaper','CF2'),...
    struct('name','LCT','namePaper','LCT'),...
    struct('name','DSST','namePaper','DSST'),...
    struct('name','MEEM','namePaper','MEEM'),...
    struct('name','KCF','namePaper','KCF'),...
    struct('name','SAMF','namePaper','SAMF'),...
    };
trackers_otb2015 = {
    struct('name','ours','namePaper','ours'),...
    struct('name','ECO','namePaper','ECO'),...
    struct('name','CCOT','namePaper','CCOT'),...
    struct('name','SRDCFdecon','namePaper','SRDCFdecon'),...
    struct('name','Staple','namePaper','Staple'),...
    struct('name','DeepSRDCF','namePaper','DeepSRDCF'),...
    struct('name','CF2','namePaper','CF2'),...
    struct('name','DSST','namePaper','DSST'),...
    struct('name','MEEM','namePaper','MEEM'),...
    struct('name','KCF','namePaper','KCF'),...
    };
if nargin == 0
    benchmark = 'otb2013';
end
switch lower(benchmark)
    case 'otb50'
        trackers = trackers_otb2015;
    case 'otb2013'
        trackers = trackers_otb2013;
    case 'otb2015'
        trackers = trackers_otb2015;
    otherwise
        trackers = trackers_otb2013;
end